export interface Event {
  id: string;
  title: string;
  description: string;
  date: Date;
  location: string;
  campus: 'Burnaby' | 'Surrey' | 'Vancouver';
  category: string;
  image?: string;
  club: string;
  clubAvatar: string;
  maxAttendees?: number;
  currentAttendees: number;
  tags: string[];
  isFree: boolean;
  cost?: number;
}

export const events: Event[] = [
  {
    id: '1',
    title: 'Web Development Workshop',
    description: 'Learn React, Next.js, and modern web development practices. Perfect for beginners! We\'ll build a real project together.',
    date: new Date('2024-01-15T18:00:00'),
    location: 'AQ 3154',
    campus: 'Burnaby',
    category: 'Technology',
    club: 'GDSC SFU',
    clubAvatar: '🎨',
    maxAttendees: 50,
    currentAttendees: 23,
    tags: ['React', 'Web Dev', 'Beginner'],
    isFree: true,
  },
  {
    id: '2',
    title: 'AI & Machine Learning Meetup',
    description: 'Explore the latest trends in AI and ML. Network with fellow students and industry professionals.',
    date: new Date('2024-01-16T19:00:00'),
    location: 'Surrey Campus Library',
    campus: 'Surrey',
    category: 'Technology',
    club: 'AI Club SFU',
    clubAvatar: '🤖',
    maxAttendees: 30,
    currentAttendees: 18,
    tags: ['AI', 'Machine Learning', 'Networking'],
    isFree: true,
  },
  {
    id: '3',
    title: 'Sustainable Business Pitch Competition',
    description: 'Pitch your eco-friendly business idea to industry judges. Win prizes and get feedback on your startup!',
    date: new Date('2024-01-18T14:00:00'),
    location: 'Harbour Centre',
    campus: 'Vancouver',
    category: 'Business',
    club: 'Enactus SFU',
    clubAvatar: '🌱',
    maxAttendees: 100,
    currentAttendees: 67,
    tags: ['Pitch', 'Sustainability', 'Startup'],
    isFree: true,
  },
  {
    id: '4',
    title: 'Women in Computing Networking Event',
    description: 'Connect with women in tech, share experiences, and build your professional network.',
    date: new Date('2024-01-20T17:30:00'),
    location: 'AQ 3156',
    campus: 'Burnaby',
    category: 'Networking',
    club: 'WiCS SFU',
    clubAvatar: '💻',
    maxAttendees: 40,
    currentAttendees: 31,
    tags: ['Women in Tech', 'Networking', 'Career'],
    isFree: true,
  },
  {
    id: '5',
    title: 'Game Development Workshop',
    description: 'Learn Unity basics and create your first game. No prior experience required!',
    date: new Date('2024-01-22T16:00:00'),
    location: 'AQ 3158',
    campus: 'Burnaby',
    category: 'Technology',
    club: 'Game Dev Club',
    clubAvatar: '🎮',
    maxAttendees: 25,
    currentAttendees: 12,
    tags: ['Unity', 'Game Dev', 'Creative'],
    isFree: true,
  },
  {
    id: '6',
    title: 'Mental Health Awareness Week Kickoff',
    description: 'Join us for a week of activities focused on mental health and wellness. Free food and resources!',
    date: new Date('2024-01-23T12:00:00'),
    location: 'Convocation Mall',
    campus: 'Burnaby',
    category: 'Health & Wellness',
    club: 'SFU Health & Wellness',
    clubAvatar: '💚',
    maxAttendees: 200,
    currentAttendees: 145,
    tags: ['Mental Health', 'Wellness', 'Community'],
    isFree: true,
  },
  {
    id: '7',
    title: 'Data Science Career Panel',
    description: 'Hear from industry professionals about careers in data science and analytics.',
    date: new Date('2024-01-25T18:30:00'),
    location: 'AQ 3155',
    campus: 'Burnaby',
    category: 'Career',
    club: 'Data Science Club',
    clubAvatar: '📊',
    maxAttendees: 60,
    currentAttendees: 42,
    tags: ['Data Science', 'Career', 'Industry'],
    isFree: true,
  },
  {
    id: '8',
    title: 'Cultural Food Festival',
    description: 'Taste foods from around the world and celebrate SFU\'s diverse community.',
    date: new Date('2024-01-27T11:00:00'),
    location: 'Maggie Benston Centre',
    campus: 'Burnaby',
    category: 'Cultural',
    club: 'International Student Association',
    clubAvatar: '🌍',
    maxAttendees: 300,
    currentAttendees: 189,
    tags: ['Food', 'Culture', 'Community'],
    isFree: true,
  },
  {
    id: '9',
    title: 'Startup Pitch Night',
    description: 'Watch student entrepreneurs pitch their startups to investors and get feedback.',
    date: new Date('2024-01-29T19:00:00'),
    location: 'Harbour Centre Room 1420',
    campus: 'Vancouver',
    category: 'Business',
    club: 'SFU Entrepreneurship',
    clubAvatar: '🚀',
    maxAttendees: 80,
    currentAttendees: 56,
    tags: ['Startup', 'Pitch', 'Investment'],
    isFree: true,
  },
  {
    id: '10',
    title: 'Climate Action Workshop',
    description: 'Learn practical ways to reduce your carbon footprint and make a positive environmental impact.',
    date: new Date('2024-01-31T15:00:00'),
    location: 'AQ 3157',
    campus: 'Burnaby',
    category: 'Environment',
    club: 'SFU Environmental Club',
    clubAvatar: '🌿',
    maxAttendees: 35,
    currentAttendees: 28,
    tags: ['Climate', 'Environment', 'Action'],
    isFree: true,
  },
];
